<?php
$targetchargers = [];
array_push($targetchargers,"Moto Southwaite North, M6 Motorway, Northbound, Jct 41/42, Broadfield Road, CarlisleDC & AC fast charge");
array_push($targetchargers,"Moto Southwaite South, M6 Motorway, Southbound, Jct 41/42, Broadfield Road, CarlisleDC & AC fast charge");
array_push($targetchargers,"Westmorland, Rheged Centre, Redhills, PenrithDC & AC fast charge");
array_push($targetchargers,"Westmorland, Tebay, M6 Motorway Northbound, Jct 38/39, Westmorland Place, Orton, PenrithDC & AC fast charge");
array_push($targetchargers,"Roadchef Killington Lake, M6 Motorway, Jct 36/37 Southbound, Nr. KendalDC & AC fast charge");
array_push($targetchargers,"Moto Burton-in-Kendal, M6 Motorway, Jct 35/36 Northbound, Burton West, CarnforthDC & AC fast charge");
array_push($targetchargers,"Moto Lancaster North, M6 Motorway Northbound, Jct 32/33, White Carr Lane, Bay Horse, LancasterDC & AC fast charge");
array_push($targetchargers,"Moto Lancaster South, M6 Motorway Southbound, Jct 32/33, White Carr Lane, Bay Horse, LancasterDC & AC fast charge");
array_push($targetchargers,"BP Ewood Service Station, Bolton Road, BlackburnDC & AC fast charge");
array_push($targetchargers,"Extra Blackburn and Darwen, M65 Motorway, Jct 4, DarwenDC & AC fast charge");
array_push($targetchargers,"IKEA Leeds, Holden Ing Way, Birstall, BatleyDC & AC fast charge");
array_push($targetchargers,"Welcome Break, Hartshead Moor, M62 Westbound, Jct 25/26, Clifton, BrighouseDC & AC fast charge");
array_push($targetchargers,"Welcome Break, Hartshead Moor, M62 Eastbound, Jct 25/26, Clifton, BrighouseDC & AC fast charge");
array_push($targetchargers,"Moto Birch West, M62 Motorway Westbound, Jct 18/19, HeywoodDC & AC fast charge");
array_push($targetchargers,"Moto Birch East, M62 Motorway Eastbound, Jct 18/19, HeywoodDC & AC fast charge");
array_push($targetchargers,"IKEA Manchester, Wellington Road, Ashton-Under-Lyne, Tameside, ManchesterDC & AC fast charge");
array_push($targetchargers,"Eurogarages, Rivington Services, M61 Motorway Southbound, BoltonDC & AC fast charge");
array_push($targetchargers,"Eurogarages, Rivington Services, M61 Motorway Northbound, BoltonDC & AC fast charge");
array_push($targetchargers,"Welcome Break Charnock Richard North, M6 Motorway Northbound, Jct 27/28, Mill Lane, ChorleyDC & AC fast charge");
array_push($targetchargers,"Welcome Break Charnock Richard South, M6 Motorway Southbound, Jct 27/28, Mill Lane, ChorleyDC & AC fast charge");
array_push($targetchargers,"Welcome Break, Burtonwood, M62 Motorway, Jct 8, Great Sankey, WarringtonDC & AC fast charge");
array_push($targetchargers,"IKEA Warrington, 910 Europa Boulevard, WestbrookDC & AC fast charge");
array_push($targetchargers,"Moto Lymm, Cliff Lane, LymmDC & AC fast charge");
array_push($targetchargers,"Roadchef Chester, M56 Motorway, Jct 14, Elton, ChesterDC & AC fast charge");
array_push($targetchargers,"Roadchef, Sandbach, M6 Motorway Northbound, Jct 16/17, Betchton, SandbachDC & AC fast charge");
array_push($targetchargers,"Roadchef, Sandbach, M6 Motorway Southbound, Jct 16/17, Betchton, SandbachDC & AC fast charge");
array_push($targetchargers,"Welcome Break Keele North, M6 Motorway Northbound, Jct 15/16, Keele, Newcastle-Under-LymeDC & AC fast charge");
array_push($targetchargers,"Welcome Break Keele South, M6 Motorway Southbound, Jct 15/16, Keele, Newcastle-Under-LymeDC & AC fast charge");
array_push($targetchargers,"Moto Stafford North, M6 Motorway Northbound, Jct 14/15, StoneDC & AC fast charge");
array_push($targetchargers,"Roadchef Stafford South, M6 Motorway, Jct 14/15 Southbound, StoneDC & AC fast charge");
array_push($targetchargers,"Moto Hilton Park North, M6 Motorway Northbound, Jct 10A/11, Essington, WolverhamptonDC & AC fast charge");
array_push($targetchargers,"Moto Hilton Park South, M6 Motorway Southbound, Jct 10A/11, Essington, WolverhamptonDC & AC fast charge");
array_push($targetchargers,"Roadchef Norton Canes, M6 Toll Motorway, Jct T6/T7, Betty's Lane, Norton Canes, CannockDC & AC fast charge");
array_push($targetchargers,"IKEA Wednesbury, Park Lane, WednesburyDC & AC fast charge");
array_push($targetchargers,"Birmingham International Airport, Drop n' Go Car Park, Bickenhill, BirminghamDC & AC fast charge");
array_push($targetchargers,"Welcome Break Corley North, M6 Motorway Northbound, Jct 3/4, Highfield Lane, CoventryDC & AC fast charge");
array_push($targetchargers,"Welcome Break Corley South, M6 Motorway Southbound, Jct 3/4, Highfield Lane, CoventryDC & AC fast charge");
array_push($targetchargers,"IKEA Coventry, 2 Croft RoadDC & AC fast charge");
array_push($targetchargers,"Welcome Break Hopwood Park, M42 Motorway, Jct 2, Redditch Road, Alvechurch, BirminghamDC & AC fast charge");

include("../../php/rss_template.php");
?>